AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - Rakefile
    - bc-lightstep-ruby.gemspec

Lint/AmbiguousOperator:
  Enabled: false

Metrics/ParameterLists:
  Max: 20

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - lib/bigcommerce/lightstep/redis/wrapper.rb

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10
