AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - Rakefile
    - bc-lightstep-ruby.gemspec
require:
  - rubocop-performance

Lint/AmbiguousOperator:
  Enabled: false

Metrics/ParameterLists:
  Max: 20

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - lib/bigcommerce/lightstep/redis/wrapper.rb

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10
