version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  ruby: bigcommerce/internal-ruby@volatile

defaults: &defaults
  notify_failure: false

ruby_3_2_defaults: &ruby_3_2_defaults
  <<: *defaults
  e:
    name: ruby/ruby
    ruby-version: '3.2'

ruby_3_3_defaults: &ruby_3_3_defaults
  <<: *defaults
  e:
    name: ruby/ruby
    ruby-version: '3.3'

ruby_3_4_defaults: &ruby_3_4_defaults
  <<: *defaults
  e:
    name: ruby/ruby
    ruby-version: '3.4'

workflows:
  version: 2
  ruby_3_2:
    jobs:
      - ruby/bundle-audit:
          <<: *ruby_3_2_defaults
          name: ruby-3_2-bundle_audit
      - ruby/rubocop:
          <<: *ruby_3_2_defaults
          name: ruby-3_2-rubocop
      - ruby/rspec-unit:
          <<: *ruby_3_2_defaults
          name: ruby-3_2-rspec_unit
          db: false
  ruby_3_3:
    jobs:
      - ruby/bundle-audit:
          <<: *ruby_3_3_defaults
          name: ruby-3_3-bundle_audit
      - ruby/rubocop:
          <<: *ruby_3_3_defaults
          name: ruby-3_3-rubocop
      - ruby/rspec-unit:
          <<: *ruby_3_3_defaults
          name: ruby-3_3-rspec_unit
          db: false
  ruby_3_4:
    jobs:
      - ruby/bundle-audit:
          <<: *ruby_3_4_defaults
          name: ruby-3_4-bundle_audit
      - ruby/rubocop:
          <<: *ruby_3_4_defaults
          name: ruby-3_4-rubocop
      - ruby/rspec-unit:
          <<: *ruby_3_4_defaults
          name: ruby-3_4-rspec_unit
          db: false
